import time

print('********音乐推荐系统********')
time.sleep(2)
print('请选择商品类目：')
print('1. 服装类')
print('2. 电器类')
print('3. 家装类')
print('4. 日用类')
print('5. 其他')
goods = int(input())
time.sleep(1)
print('****正在努力为您匹配合适的BGM****')
time.sleep(3)
print('**以下是系统推荐的BGM：**')
print('   音乐    ---    推荐指数')
print('')
print('1. 音乐1   ---      9.0')
print('2. 音乐2   ---      8.8')
print('3. 音乐3   ---      8.7')
print('4. 音乐4   ---      8.5')
print('5. 音乐5   ---      8.4')
print('')
time.sleep(2)
while True:
    print('请选择您要进行的操作：')
    print('1. 显示更多')
    print('2. 选择音乐')
    judge = int(input())
    if judge == 1:
        print('   音乐    ---    推荐指数')
        print('')
        print('6. 音乐6   ---      8.2')
        print('7. 音乐7   ---      7.8')
        print('8. 音乐8   ---      7.7')
        print('9. 音乐9   ---      7.5')
        print('10.音乐10  ---      7.4')
    else:
        print('您要选择的音乐序号是：')
        order = int(input())
        time.sleep(2)
        while True:
            print('您可以进行如下操作：')
            print('1. 试听音乐')
            print('2. 采纳音乐')
            print('3. 点赞')
            print('4. 点踩')
            choose = int(input())
            if choose == 1:
                time.sleep(2)
                print('*音乐播放中*')
                time.sleep(5)
                print('*试听结束*')
                time.sleep(2)
                print('')
            elif choose == 2:
                time.sleep(2)
                print('*小提示*该音乐配合xx类带货视频往往能起到xx效果，但我们更推荐你选用快节奏的音乐')
                exit(1)
            elif choose == 3:
                time.sleep(2)
                print('*您的反馈已收到，在今后相关类目的推荐中，我们将考虑优先推荐该背景音乐*')
                time.sleep(2)
                print('')
            else:
                time.sleep(2)
                print('*您的反馈已收到，在今后相关类目的推荐中，我们将尽量少推荐该背景音乐*')
                time.sleep(2)
                print('')
